### ISSUE TITLE
Should fbjs be a peer dependency?

### ISSUE THREAD

**Issue by jondlm** [namuol/react-declarative-styles#3]
I'm very leery of peer dependencies because of the complexity they introduce when it comes time to upgrade apps. Why isn't `fbjs` just a regular dependency? Looks like it's only being used for `warning` and `invariant`. It's not clear to me why those need to be a peer dep.

**Comment by namuol** [comment]
While we're on the subject, [we shouldn't even be using `fbjs`](https://github.com/facebook/fbjs/blob/d2dd31dbb7b969a7b17795b6eff99c6ac20ad04c/README.md#purpose).

I think the right course of action may be to have normal dependencies on "mirror" implementations of [`warning`](https://www.npmjs.com/package/warning) and [`invariant`](https://www.npmjs.com/package/invariant).

**Comment by jondlm** [comment]
Awesome, that looks much better :+1: Thank you!

**Comment by namuol** [comment]
Thanks for the suggestion :) If you end up using Seamstress let me know. :beers:
