### ISSUE TITLE
style function cached?

### ISSUE THREAD

**Issue by jhsu** [namuol/react-declarative-styles#4]
Haven't had time to check what happens when a style function is provided, but on subsequent renders the style function doesn't seem to be called again.

I tested this buy putting a console.log in the style function and putting

```
componentDidMount() {
  setTimeout(() => {
    this.forceUpdate();
  }, 2000);
}
```

**Comment by namuol** [comment]
Just to clarify, did you mean this?

> Haven't had time to check what happens when a style function **isn't** provided

**Comment by jhsu** [comment]
@namuol nope I meant that my style config looks something like:

```
{
  style: ({props}) => {
    return {
      ':base': {color: 'white'}
    }
  }
}
```

so I started thinking, and realized that since we wrap our react component, calling `this.forceUpdate()` within the component won't result in the `getComputedStyles` function getting called, because it force updates the component and _not_ the seamstress wrapped component.

So somehow, I'd like to have the seamstress component pass in new computedStyles.

One possibility is to pass down a prop to the wrapped react component.

```
        render () {
          const { props, context } = this;
          return <Component
            forceUpdate={this.forceUpdate.bind(this)}
            {...props}
            computedStyles={getComputedStyles({props, context})}
          />;
        }
```

so that the wrapped component can force seamstress to recompute styles

The reason i'm doing this is because I have a singleton that holds some theme variables that can get set by the user, and when that changes, i'd like the seamstress wrapped components to update.

**Comment by namuol** [comment]
Ah. In that case, I think you'd be better served to "pre-compute" the main `styles` prop in your own wrapper component, rather than use a `styles` callback.

The `styles` callback is really only meant as an "escape hatch" for special behavior that isn't a direct result of a change in state/props.

In fact, using a HoC is probably the saner approach in all cases... I may just remove the callback feature entirely, as it kinda defeats the purpose of having declarative styles.

**Comment by jhsu** [comment]
(sorry for the spam =P)

@namuol hmm ok, yeah I could try that, was hoping I could avoid having more wrappers, but I'll give it a try, thanks!

**Comment by namuol** [comment]
Did you try using `Seamstress.createDecorator`? That should work.

**Comment by jhsu** [comment]
oh I haven't, that actually might do it since it provides `getComputedStyles()`, not sure why I didn't

**Comment by jhsu** [comment]
awesome, it works great, thanks a bunch! here's it working (there's a setTimeout that changes the color to red):

![force update](http://cl.ly/0F343N3T3d2E/Screen%20Recording%202016-02-08%20at%2002.36%20PM.gif)

**Comment by namuol** [comment]
Great! Glad that helped. :beers: I'll be sure to make a clear distinction between `createDecorator` and `createContainer` when I get a chance to write a guide.
